version: '3'

services: 

  nodeapp:
    image: hmullermail/fc_02_nodeapp
    container_name: nodeapp
    networks:
      - node-network
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: node index.js
    depends_on:
      - db


  proxy:
    image: hmullermail/fc_02_proxy
    container_name: proxy
    ports:
      - "8080:80"
    networks:
      - node-network
    depends_on:
      - nodeapp


  db:
    image: hmullermail/fc_02_db
    container_name : db
    restart: always
    volumes:
      - ./db/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge

