version: '3'

services: 

  nodeapp:
    build: 
      context: nodeapp
      dockerfile: Dockerfile.prod
    container_name: nodeapp
    networks:
      - node-network
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: node index.js
    depends_on:
      - db


  proxy:
    build:
      context: proxy
    container_name: proxy
    ports:
      - "8080:80"
    networks:
      - node-network
    depends_on:
      - nodeapp


  db:
    build:
      context: db
    container_name : db
    restart: always
    volumes:
      - ./db/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge

